### ISSUE TITLE
error: inlining failed in call to ‘always_inline’ ‘__m256i _mm256_cmpeq_epi8(__m256i, __m256i)’: target specific option mismatch (GCC 12, debug)

### ISSUE THREAD

**Issue by hansingt** [simdutf/simdutf#578] opened 2024-10-09 11:19 UTC
I'm currently trying to compile the latest version(s) of simdutf in a [Python Manylinux](https://github.com/pypa/manylinux) 2.28 container (`quay.io/pypa/manylinux_2_28_x86_64`).

The container is based on AlmaLinux 8 and uses gcc 12.2.1 and binutils 2.30.

When trying to do a Debug build of the library, I get the following error:

```
[ 50%] Building CXX object src/CMakeFiles/simdutf.dir/simdutf.cpp.o
In file included from /root/simdutf/src/simdutf/haswell/simd.h:494,
                 from /root/simdutf/src/simdutf/haswell.h:58,
                 from /root/simdutf/src/implementation.cpp:26,
                 from /root/simdutf/src/simdutf.cpp:4:
/root/simdutf/src/simdutf/haswell/simd16-inl.h: In function ‘simdutf::haswell::{anonymous}::simd::simd16<bool> simdutf::haswell::{anonymous}::simd::operator==(simd16<short unsigned int>, simd16<short unsigned int>)’:
/root/simdutf/src/simdutf/haswell/simd16-inl.h:24:37: note: the ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
   24 |   friend simdutf_really_inline Mask operator==(const simd16<T> lhs,
      |                                     ^~~~~~~~
/root/simdutf/src/simdutf/haswell/simd16-inl.h:26:39: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
   26 |     return _mm256_cmpeq_epi16(lhs, rhs);
      |                                       ^
In file included from /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/immintrin.h:47,
                 from /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/x86intrin.h:32,
                 from /root/simdutf/src/simdutf/icelake/intrinsics.h:20,
                 from /root/simdutf/src/simdutf/icelake.h:59,
                 from /root/simdutf/src/implementation.cpp:25:
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/avx2intrin.h: In function ‘simdutf::haswell::{anonymous}::simd::simd8<bool> simdutf::haswell::{anonymous}::simd::operator==(simd8<unsigned char>, simd8<unsigned char>)’:
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/avx2intrin.h:231:1: error: inlining failed in call to ‘always_inline’ ‘__m256i _mm256_cmpeq_epi8(__m256i, __m256i)’: target specific option mismatch
  231 | _mm256_cmpeq_epi8 (__m256i __A, __m256i __B)
      | ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [src/CMakeFiles/simdutf.dir/build.make:76: src/CMakeFiles/simdutf.dir/simdutf.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:872: src/CMakeFiles/simdutf.dir/all] Error 2
gmake: *** [Makefile:146: all] Error **2**
```

<details><summary>Host details</summary>

```
> cat /etc/fedora-release
Fedora release 40 (Forty)

> uname -a 
Linux <redicted> 6.10.12-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 30 21:38:25 UTC 2024 x86_64 GNU/Linux

> cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 80
model name	: AMD Ryzen 7 PRO 5850U with Radeon Graphics
stepping	: 0
microcode	: 0xa50000f
cpu MHz		: 2894.128
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass srso
bogomips	: 3792.44
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
[...]
```
</details>

<details><summary>Commands to reproduce the issue</summary>

```shell
> podman run --rm -it quay.io/pypa/manylinux_2_28_x86_64:latest
$ git clone https://github.com/simdutf/simdutf $HOME/simdutf
$ cd $HOME/simdutf
$ cmake -B build -DCMAKE_BUILD_TYPE=Debug -DSIMDUTF_TESTS=OFF -DSIMDUTF_BENCHMARKS=OFF -DSIMDUTF_TOOLS=OFF
$ cmake --build build -j
```

Instead of `podman`, e.g. `docker` could be used as well, of course.
</details>

The issue seems to be introduced in v5.3.2. Versions up until v5.3.1 compile without error using this approach.

Do you have any idea, why this could happen and how to fix this?

The issue araised to me when trying to include simdutf in another project using vcpkg. I've reported the issue to vcpkg as well (https://github.com/microsoft/vcpkg/issues/41440).

**Comment by lemire** [comment] 2024-10-09 14:39
Please try to verify the issue with simdutf 5.5.0 (current latest version).

**Comment by lemire** [comment] 2024-10-09 14:49
Tested with current release. I cannot reproduce. Please test the following:

```
[dlemire@fedora-40]$  curl -OL https://github.com/simdutf/simdutf/releases/download/v5.5.0/singleheader.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  218k  100  218k    0     0   530k      0 --:--:-- --:--:-- --:--:--  530k
[dlemire@fedora-40]$ unzip singleheader.zip
[dlemire@fedora-40]$ c++ amalgamation_demo.cpp
[dlemire@fedora-40]$ ./a.out
valid UTF-8
wrote 4 UTF-16LE words.valid UTF-16LE
wrote 4 UTF-8 words.1234
perfect round trip
```

**Comment by lemire** [comment] 2024-10-09 21:17
I am going to close this issue as I cannot reproduce it. Note that Node.js builds against version 5.5.0 https://github.com/nodejs/node/commit/bf4bf7cc6b, and it has built against various versions before.

A new issue with additional details is invited.

**Comment by hansingt** [comment] 2024-10-10 05:18
Sorry for the late reply, seems like we're living in different timezones ;)

I might not have been clear in my first post, but:

1) I'm unable to build *any* version down to 5.3.1. I've tried with 5.5.0 as well as latest HEAD.
2) Besides my host is running Fedora 40, I'm not building on it. I'm using the `quay.io/pypa/manylinux_2_28_x86_64` container for building. Building on Fedora 40 works as expected.
3) The issue only occurrs for *debug* builds. Release builds work as expected.

That being said, I can reproduce the issue with you demo as well:

```
[root@0692abd87a4c ~]# curl -OL https://github.com/simdutf/simdutf/releases/download/v5.5.0/singleheader.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  218k  100  218k    0     0   170k      0  0:00:01  0:00:01 --:--:--  601k
[root@0692abd87a4c ~]# unzip singleheader.zip 
Archive:  singleheader.zip
  inflating: simdutf.cpp             
  inflating: simdutf.h               
  inflating: amalgamation_demo.cpp   
[root@0692abd87a4c ~]# ls
amalgamation_demo.cpp  simdutf.cpp  simdutf.h  singleheader.zip
[root@0692abd87a4c ~]# c++ amalgamation_demo.cpp 
In file included from amalgamation_demo.cpp:3:
simdutf.cpp: In function ‘simdutf::haswell::{anonymous}::simd::simd16<bool> simdutf::haswell::{anonymous}::simd::operator==(simd16<short unsigned int>, simd16<short unsigned int>)’:
simdutf.cpp:2816:37: note: the ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
 2816 |   friend simdutf_really_inline Mask operator==(const simd16<T> lhs, const simd16<T> rhs) { return _mm256_cmpeq_epi16(lhs, rhs); }
      |                                     ^~~~~~~~
simdutf.cpp:2816:126: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
 2816 |   friend simdutf_really_inline Mask operator==(const simd16<T> lhs, const simd16<T> rhs) { return _mm256_cmpeq_epi16(lhs, rhs); }
      |                                                                                                                              ^
In file included from /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/immintrin.h:47,
                 from /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/x86intrin.h:32,
                 from simdutf.cpp:1861:
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/avx2intrin.h: In function ‘simdutf::haswell::{anonymous}::simd::simd8<bool> simdutf::haswell::{anonymous}::simd::operator==(simd8<unsigned char>, simd8<unsigned char>)’:
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/avx2intrin.h:231:1: error: inlining failed in call to ‘always_inline’ ‘__m256i _mm256_cmpeq_epi8(__m256i, __m256i)’: target specific option mismatch
  231 | _mm256_cmpeq_epi8 (__m256i __A, __m256i __B)
      | ^~~~~~~~~~~~~~~~~
simdutf.cpp:2469:125: note: called from here
 2469 |     friend simdutf_really_inline Mask operator==(const simd8<T> lhs, const simd8<T> rhs) { return _mm256_cmpeq_epi8(lhs, rhs); }
      |                                                                                                                             ^
[root@0692abd87a4c ~]# 

```

I'm well aware, that some large projects are using your library and that the issue might (or even most likely) will be in the build environment, but I can't find, what's wrong. The container should meet all [requirements](https://github.com/simdutf/simdutf?tab=readme-ov-file#requirements) you've listed.

I really would appreciate some help here. Thanks in advance!

**Comment by hansingt** [comment] 2024-10-10 05:25
As you're using Fedora as well, you will most likely have `podman` installed as well.

If so, here is a short oneliner to reproduce the issue:

```
podman run --rm quay.io/pypa/manylinux_2_28_x86_64:latest bash -c "curl -OL https://github.com/simdutf/simdutf/releases/download/v5.5.0/singleheader.zip; unzip singleheader.zip; c++ amalgamation_demo.cpp"
```

**Comment by hansingt** [comment] 2024-10-10 05:41
I think, I might have found the issue. The code seems to assume, that AVX is always enabled, but the platform doesn't enable it by default.

If enable it explicitly using `-march=native`, compilation works:

```
[root@eb9393448e17 ~]# curl -OL https://github.com/simdutf/simdutf/releases/download/v5.5.0/singleheader.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  218k  100  218k    0     0   309k      0 --:--:-- --:--:-- --:--:--  309k
[root@eb9393448e17 ~]# unzip singleheader.zip 
Archive:  singleheader.zip
  inflating: simdutf.cpp             
  inflating: simdutf.h               
  inflating: amalgamation_demo.cpp   
[root@eb9393448e17 ~]# c++ -march=native amalgamation_demo.cpp 
[root@eb9393448e17 ~]# ./a.out 
valid UTF-8
wrote 4 UTF-16LE words.valid UTF-16LE
wrote 4 UTF-8 words.1234
perfect round trip
```

**Comment by hansingt** [comment] 2024-10-10 11:38
In fact, this seems to be an issue when compiling with GCC 12.

Explicitly using GCC 12 on my Fedora Host (via [Homebrew](https://formulae.brew.sh/formula/gcc@12)) gives the same results.

The `avx2intrin.h:231` mentioned in the errors contains the following definition:

```c
extern __inline __m256i
__attribute__ ((__gnu_inline__, __always_inline__, __artificial__))
_mm256_cmpeq_epi8 (__m256i __A, __m256i __B)
{
  return (__m256i) ((__v32qi)__A == (__v32qi)__B);
}
```

This led me to checking the definition of the [`simdutf_really_inline`](https://github.com/simdutf/simdutf/blob/2f2818858a1342ad2549eb91d1bdcfd7fd1126b1/include/simdutf/common_defs.h#L70) macro. This led me to the following commit: https://github.com/simdutf/simdutf/commit/04b9b9ed1a698a161c71a6f901041735f19cd93b, which introduces a distinction between optimized (release) and unoptimized (debug) builds regarding the inlining of functions.

Maybe, this is the root cause of the problem? At least, the change mentioned above is introduced in 5.3.2, which matches my findings.

I'm not sure, what effect `-mavx2` has, but either using this, or using `-O` allows to compile.

**Comment by lemire** [comment] 2024-10-10 17:26
Looks like there might be a compiler bug.

**Closed** 2024-10-10 23:42 UTC
