### ISSUE TITLE
Compiling with clang on windows fails

### ISSUE THREAD

**Issue by romanholidaypancakes** [simdutf/simdutf#224] opened 2023-04-01 04:53 UTC
clang version: [download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe)

```
simdutf/simdutf.h:745:25: error: too few arguments provided to function-like      macro invocation
  __cpuid(cpu_info, *eax);
                        ^
D:\Program Files\LLVM\lib\clang\16\include\cpuid.h:258:9: note: macro '__cpuid' defined here


simdutf/simdutf.h:745:3: error: builtin functions must be directly called   
  __cpuid(cpu_info, *eax);
  ^
```

**Comment by lemire** [comment] 2023-04-03 01:30
The signature of the `__cpuid` function is...

```
void __cpuid(
   int cpuInfo[4],
   int function_id
);
```

It is defined in LLVM as such...
https://github.com/llvm/llvm-project/blob/466d554dcab39c3d42fe0c5b588b795e0e4b9d0d/clang/lib/Headers/intrin.h#L60


In the piece of code that you refer to, we call it as such...

```
  int cpu_info[4];
  __cpuid(cpu_info, *eax);
```

So our usage is correct given the `intrin.h` header that must be included when `defined(_MSC_VER)` is true (see https://github.com/simdutf/simdutf/blob/26acc10b7ecaccce40eae32762e247d07d7f2ef2/include/simdutf/internal/isadetection.h#L51), and the only way we call `__cpuid` is if `defined(_MSC_VER)` is true.


You are getting an error in `cpuid.h` but we do not include `cpuid.h` if `defined(_MSC_VER)` is true:

```
#if defined(_MSC_VER)
#include <intrin.h>
#elif defined(HAVE_GCC_GET_CPUID) && defined(USE_GCC_GET_CPUID)
#include <cpuid.h>
#endif
```

In continuous integration, we support compiling with clang using msys2 and under Visual Studio (using ClangCL). 

https://github.com/simdutf/simdutf/blob/master/.github/workflows/msys2-clang.yml

and

https://github.com/simdutf/simdutf/blob/master/.github/workflows/vs17-clang-ci.yml

Thus we support building simdutf with clang using two different approaches: msys2 and visual-studio/clangcl.

Hence, it is not correct to say that "Compiling with clang on windows fails". It does. We even have users who have production code compiled with LLVM under Windows.

You seem to be getting a build error. Please consider contributing a CI tests (see above). If you believe that there is a bug in our code, please consider producing a pull request.

I am closing this, as there is insufficient details for us to reproduce the issue, and because we do build every commit under Windows with LLVM under two reasonable settings (Visual Studio/clang and msys2).

If you believe I am in error, please open a new issue, but provide complete details.

**Closed by lemire** 2023-04-03 01:30 UTC
